FROM eclipse-temurin:8-jre-alpine
WORKDIR /app

# On installe bash si nécessaire pour exécuter les commandes à la suite
RUN apk add --no-cache bash

# On copie le JAR du serveur
COPY corba-server/target/corba-server.jar app.jar

# On lance d'abord le service de noms CORBA par défaut (orbd ou tnameserv) en arrière-plan, 
# on attend 3 secondes qu'il soit prêt, puis on démarre votre JAR.
CMD tnameserv -ORBInitialPort 2809 & sleep 4 && java -jar app.jar
