# =============================================================
# application.properties — Middleware Spring Boot
# =============================================================

server.port=${WEB_PORT:8080}

# Taille max des fichiers uploadés (50 Mo)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# CORBA / Naming Service
corba.naming.host=${NAMING_HOST:naming}
corba.naming.port=${NAMING_PORT:2809}
corba.server.port=${SERVER_PORT:2810}

# Retry connexion CORBA au démarrage
corba.retry.max=20
corba.retry.delay-ms=3000

# CORS — autorise le frontend
spring.web.cors.allowed-origins=*

# Logging
logging.level.com.pdfservice=INFO
logging.level.org.jacorb=WARN
