package PDFService;


/**
* PDFService/ByteArrayListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:40 PM GMT
*/

public final class ByteArrayListHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[][] = null;

  public ByteArrayListHolder ()
  {
  }

  public ByteArrayListHolder (byte[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.ByteArrayListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.ByteArrayListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.ByteArrayListHelper.type ();
  }

}
