package PDFService;

/**
* PDFService/CompressionParamsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:42 PM GMT
*/

public final class CompressionParamsHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.CompressionParams value = null;

  public CompressionParamsHolder ()
  {
  }

  public CompressionParamsHolder (PDFService.CompressionParams initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.CompressionParamsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.CompressionParamsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.CompressionParamsHelper.type ();
  }

}
