package PDFService;


/**
* PDFService/CompressionParams.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:42 PM GMT
*/

public final class CompressionParams implements org.omg.CORBA.portable.IDLEntity
{
  public int dpi = (int)0;

  // résolution images (ex: 150)
  public boolean compressImages = false;
  public boolean removeMetadata = false;

  public CompressionParams ()
  {
  } // ctor

  public CompressionParams (int _dpi, boolean _compressImages, boolean _removeMetadata)
  {
    dpi = _dpi;
    compressImages = _compressImages;
    removeMetadata = _removeMetadata;
  } // ctor

} // class CompressionParams
