package PDFService;

/**
* PDFService/EmbeddedImageResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:43 PM GMT
*/

public final class EmbeddedImageResultHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.EmbeddedImageResult value = null;

  public EmbeddedImageResultHolder ()
  {
  }

  public EmbeddedImageResultHolder (PDFService.EmbeddedImageResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.EmbeddedImageResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.EmbeddedImageResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.EmbeddedImageResultHelper.type ();
  }

}
