package PDFService;


/**
* PDFService/EmbeddedImageResultHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:43 PM GMT
*/

abstract public class EmbeddedImageResultHelper
{
  private static String  _id = "IDL:PDFService/EmbeddedImageResult:1.0";

  public static void insert (org.omg.CORBA.Any a, PDFService.EmbeddedImageResult that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PDFService.EmbeddedImageResult extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (PDFService.ByteArrayHelper.id (), "ByteArray", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (PDFService.ByteArrayListHelper.id (), "ByteArrayList", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "images",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (PDFService.StringListHelper.id (), "StringList", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "mimeTypes",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "imageCount",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (PDFService.EmbeddedImageResultHelper.id (), "EmbeddedImageResult", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PDFService.EmbeddedImageResult read (org.omg.CORBA.portable.InputStream istream)
  {
    PDFService.EmbeddedImageResult value = new PDFService.EmbeddedImageResult ();
    value.images = PDFService.ByteArrayListHelper.read (istream);
    value.mimeTypes = PDFService.StringListHelper.read (istream);
    value.imageCount = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PDFService.EmbeddedImageResult value)
  {
    PDFService.ByteArrayListHelper.write (ostream, value.images);
    PDFService.StringListHelper.write (ostream, value.mimeTypes);
    ostream.write_long (value.imageCount);
  }

}
