package PDFService;

/**
* PDFService/ImageConversionResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:43 PM GMT
*/

public final class ImageConversionResultHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.ImageConversionResult value = null;

  public ImageConversionResultHolder ()
  {
  }

  public ImageConversionResultHolder (PDFService.ImageConversionResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.ImageConversionResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.ImageConversionResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.ImageConversionResultHelper.type ();
  }

}
