package PDFService;


/**
* PDFService/InvalidParameterException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:41 PM GMT
*/

public final class InvalidParameterException extends org.omg.CORBA.UserException
{
  public String paramName = null;
  public String reason = null;

  public InvalidParameterException ()
  {
    super(InvalidParameterExceptionHelper.id());
  } // ctor

  public InvalidParameterException (String _paramName, String _reason)
  {
    super(InvalidParameterExceptionHelper.id());
    paramName = _paramName;
    reason = _reason;
  } // ctor


  public InvalidParameterException (String $reason, String _paramName, String _reason)
  {
    super(InvalidParameterExceptionHelper.id() + "  " + $reason);
    paramName = _paramName;
    reason = _reason;
  } // ctor

} // class InvalidParameterException
