package PDFService;


/**
* PDFService/LongListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:40 PM GMT
*/

public final class LongListHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public LongListHolder ()
  {
  }

  public LongListHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.LongListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.LongListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.LongListHelper.type ();
  }

}
