package PDFService;

/**
* PDFService/PDFEncryptionExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:41 PM GMT
*/

public final class PDFEncryptionExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.PDFEncryptionException value = null;

  public PDFEncryptionExceptionHolder ()
  {
  }

  public PDFEncryptionExceptionHolder (PDFService.PDFEncryptionException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.PDFEncryptionExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.PDFEncryptionExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.PDFEncryptionExceptionHelper.type ();
  }

}
