package PDFService;


/**
* PDFService/PDFMetadata.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:42 PM GMT
*/

public final class PDFMetadata implements org.omg.CORBA.portable.IDLEntity
{
  public String title = null;
  public String author = null;
  public String subject = null;
  public String creator = null;
  public int pageCount = (int)0;
  public int fileSizeBytes = (int)0;
  public boolean isEncrypted = false;
  public String pdfVersion = null;

  public PDFMetadata ()
  {
  } // ctor

  public PDFMetadata (String _title, String _author, String _subject, String _creator, int _pageCount, int _fileSizeBytes, boolean _isEncrypted, String _pdfVersion)
  {
    title = _title;
    author = _author;
    subject = _subject;
    creator = _creator;
    pageCount = _pageCount;
    fileSizeBytes = _fileSizeBytes;
    isEncrypted = _isEncrypted;
    pdfVersion = _pdfVersion;
  } // ctor

} // class PDFMetadata
