package PDFService;

/**
* PDFService/PDFProcessingExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:41 PM GMT
*/

public final class PDFProcessingExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.PDFProcessingException value = null;

  public PDFProcessingExceptionHolder ()
  {
  }

  public PDFProcessingExceptionHolder (PDFService.PDFProcessingException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.PDFProcessingExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.PDFProcessingExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.PDFProcessingExceptionHelper.type ();
  }

}
