package PDFService;

/**
* PDFService/RotationParamsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:42 PM GMT
*/

public final class RotationParamsHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.RotationParams value = null;

  public RotationParamsHolder ()
  {
  }

  public RotationParamsHolder (PDFService.RotationParams initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.RotationParamsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.RotationParamsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.RotationParamsHelper.type ();
  }

}
