package PDFService;


/**
* PDFService/SplitResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:43 PM GMT
*/

public final class SplitResult implements org.omg.CORBA.portable.IDLEntity
{
  public byte parts[][] = null;
  public int partCount = (int)0;

  public SplitResult ()
  {
  } // ctor

  public SplitResult (byte[][] _parts, int _partCount)
  {
    parts = _parts;
    partCount = _partCount;
  } // ctor

} // class SplitResult
