package PDFService;

/**
* PDFService/TextExtractionResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:43 PM GMT
*/

public final class TextExtractionResultHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.TextExtractionResult value = null;

  public TextExtractionResultHolder ()
  {
  }

  public TextExtractionResultHolder (PDFService.TextExtractionResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.TextExtractionResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.TextExtractionResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.TextExtractionResultHelper.type ();
  }

}
