package PDFService;


/**
* PDFService/TextExtractionResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:43 PM GMT
*/

public final class TextExtractionResult implements org.omg.CORBA.portable.IDLEntity
{
  public String fullText = null;
  public String pageTexts[] = null;

  // texte par page
  public int pageCount = (int)0;

  public TextExtractionResult ()
  {
  } // ctor

  public TextExtractionResult (String _fullText, String[] _pageTexts, int _pageCount)
  {
    fullText = _fullText;
    pageTexts = _pageTexts;
    pageCount = _pageCount;
  } // ctor

} // class TextExtractionResult
