package PDFService;


/**
* PDFService/ImageConversionResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:43 PM GMT
*/

public final class ImageConversionResult implements org.omg.CORBA.portable.IDLEntity
{
  public byte images[][] = null;

  // une image par page
  public String mimeTypes[] = null;

  // "image/png" pour chaque image
  public int pageCount = (int)0;

  public ImageConversionResult ()
  {
  } // ctor

  public ImageConversionResult (byte[][] _images, String[] _mimeTypes, int _pageCount)
  {
    images = _images;
    mimeTypes = _mimeTypes;
    pageCount = _pageCount;
  } // ctor

} // class ImageConversionResult
