package PDFService;

/**
* PDFService/InvalidParameterExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:41 PM GMT
*/

public final class InvalidParameterExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.InvalidParameterException value = null;

  public InvalidParameterExceptionHolder ()
  {
  }

  public InvalidParameterExceptionHolder (PDFService.InvalidParameterException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.InvalidParameterExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.InvalidParameterExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.InvalidParameterExceptionHelper.type ();
  }

}
