package PDFService;

/**
* PDFService/IPDFServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:44 PM GMT
*/


// ----------------------------------------------------------
public final class IPDFServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.IPDFService value = null;

  public IPDFServiceHolder ()
  {
  }

  public IPDFServiceHolder (PDFService.IPDFService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.IPDFServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.IPDFServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.IPDFServiceHelper.type ();
  }

}
