package PDFService;


/**
* PDFService/IPDFService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:44 PM GMT
*/


// ----------------------------------------------------------
public interface IPDFService extends IPDFServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPDFService
