package PDFService;


/**
* PDFService/PDFEncryptionException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:42 PM GMT
*/

public final class PDFEncryptionException extends org.omg.CORBA.UserException
{
  public String message = null;

  public PDFEncryptionException ()
  {
    super(PDFEncryptionExceptionHelper.id());
  } // ctor

  public PDFEncryptionException (String _message)
  {
    super(PDFEncryptionExceptionHelper.id());
    message = _message;
  } // ctor


  public PDFEncryptionException (String $reason, String _message)
  {
    super(PDFEncryptionExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class PDFEncryptionException
