package PDFService;

/**
* PDFService/PDFMetadataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:42 PM GMT
*/

public final class PDFMetadataHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.PDFMetadata value = null;

  public PDFMetadataHolder ()
  {
  }

  public PDFMetadataHolder (PDFService.PDFMetadata initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.PDFMetadataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.PDFMetadataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.PDFMetadataHelper.type ();
  }

}
