package PDFService;


/**
* PDFService/PDFProcessingException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:41 PM GMT
*/

public final class PDFProcessingException extends org.omg.CORBA.UserException
{
  public String message = null;
  public String errorCode = null;

  public PDFProcessingException ()
  {
    super(PDFProcessingExceptionHelper.id());
  } // ctor

  public PDFProcessingException (String _message, String _errorCode)
  {
    super(PDFProcessingExceptionHelper.id());
    message = _message;
    errorCode = _errorCode;
  } // ctor


  public PDFProcessingException (String $reason, String _message, String _errorCode)
  {
    super(PDFProcessingExceptionHelper.id() + "  " + $reason);
    message = _message;
    errorCode = _errorCode;
  } // ctor

} // class PDFProcessingException
