package PDFService;

/**
* PDFService/PDFPasswordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:41 PM GMT
*/

public final class PDFPasswordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.PDFPasswordException value = null;

  public PDFPasswordExceptionHolder ()
  {
  }

  public PDFPasswordExceptionHolder (PDFService.PDFPasswordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.PDFPasswordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.PDFPasswordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.PDFPasswordExceptionHelper.type ();
  }

}
