package PDFService;


/**
* PDFService/PDFPasswordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:41 PM GMT
*/

public final class PDFPasswordException extends org.omg.CORBA.UserException
{
  public String message = null;

  public PDFPasswordException ()
  {
    super(PDFPasswordExceptionHelper.id());
  } // ctor

  public PDFPasswordException (String _message)
  {
    super(PDFPasswordExceptionHelper.id());
    message = _message;
  } // ctor


  public PDFPasswordException (String $reason, String _message)
  {
    super(PDFPasswordExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class PDFPasswordException
