package PDFService;


/**
* PDFService/RotationParams.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:42 PM GMT
*/

public final class RotationParams implements org.omg.CORBA.portable.IDLEntity
{
  public int pages[] = null;

  // numéros de pages (base 1), vide = toutes
  public int degrees = (int)0;

  public RotationParams ()
  {
  } // ctor

  public RotationParams (int[] _pages, int _degrees)
  {
    pages = _pages;
    degrees = _degrees;
  } // ctor

} // class RotationParams
