package PDFService;

/**
* PDFService/SplitResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:43 PM GMT
*/

public final class SplitResultHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.SplitResult value = null;

  public SplitResultHolder ()
  {
  }

  public SplitResultHolder (PDFService.SplitResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.SplitResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.SplitResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.SplitResultHelper.type ();
  }

}
