package PDFService;


/**
* PDFService/WatermarkParams.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:42 PM GMT
*/

public final class WatermarkParams implements org.omg.CORBA.portable.IDLEntity
{
  public String text = null;
  public float fontSize = (float)0;
  public float opacity = (float)0;
  public float rotationDegrees = (float)0;
  public int colorR = (int)0;
  public int colorG = (int)0;
  public int colorB = (int)0;
  public boolean applyToAllPages = false;
  public int targetPages[] = null;

  public WatermarkParams ()
  {
  } // ctor

  public WatermarkParams (String _text, float _fontSize, float _opacity, float _rotationDegrees, int _colorR, int _colorG, int _colorB, boolean _applyToAllPages, int[] _targetPages)
  {
    text = _text;
    fontSize = _fontSize;
    opacity = _opacity;
    rotationDegrees = _rotationDegrees;
    colorR = _colorR;
    colorG = _colorG;
    colorB = _colorB;
    applyToAllPages = _applyToAllPages;
    targetPages = _targetPages;
  } // ctor

} // class WatermarkParams
