package PDFService;

/**
* PDFService/WatermarkParamsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* Sunday, May 3, 2026 1:25:42 PM GMT
*/

public final class WatermarkParamsHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.WatermarkParams value = null;

  public WatermarkParamsHolder ()
  {
  }

  public WatermarkParamsHolder (PDFService.WatermarkParams initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.WatermarkParamsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.WatermarkParamsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.WatermarkParamsHelper.type ();
  }

}
