package com.pdfservice.corba;


/**
* com/pdfservice/corba/_IPDFServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:48 AM GMT
*/


// ----------------------------------------------------------
public class _IPDFServiceStub extends org.omg.CORBA.portable.ObjectImpl implements com.pdfservice.corba.IPDFService
{


  /**
           * Fusionne plusieurs PDFs en un seul.
           * @param pdfFiles  liste de PDF en bytes
           * @return          PDF fusionné en bytes
           */
  public byte[] merge (byte[][] pdfFiles) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("merge", true);
                com.pdfservice.corba.ByteArrayListHelper.write ($out, pdfFiles);
                $in = _invoke ($out);
                byte $result[] = com.pdfservice.corba.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/InvalidParameterException:1.0"))
                    throw com.pdfservice.corba.InvalidParameterExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return merge (pdfFiles        );
            } finally {
                _releaseReply ($in);
            }
  } // merge


  /**
           * Découpe un PDF en plusieurs fichiers selon un intervalle.
           * @param pdfFile       PDF source en bytes
           * @param pagesPerPart  nombre de pages par partie
           * @return              SplitResult avec liste de PDFs
           */
  public com.pdfservice.corba.SplitResult split (byte[] pdfFile, int pagesPerPart) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("split", true);
                com.pdfservice.corba.ByteArrayHelper.write ($out, pdfFile);
                $out.write_long (pagesPerPart);
                $in = _invoke ($out);
                com.pdfservice.corba.SplitResult $result = com.pdfservice.corba.SplitResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/InvalidParameterException:1.0"))
                    throw com.pdfservice.corba.InvalidParameterExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/PDFPasswordException:1.0"))
                    throw com.pdfservice.corba.PDFPasswordExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return split (pdfFile, pagesPerPart        );
            } finally {
                _releaseReply ($in);
            }
  } // split


  /**
           * Extrait des pages spécifiques dans un nouveau PDF.
           * @param pdfFile   PDF source en bytes
           * @param pages     liste de numéros de pages (base 1)
           * @return          PDF avec les pages extraites
           */
  public byte[] extractPages (byte[] pdfFile, int[] pages) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extractPages", true);
                com.pdfservice.corba.ByteArrayHelper.write ($out, pdfFile);
                com.pdfservice.corba.LongListHelper.write ($out, pages);
                $in = _invoke ($out);
                byte $result[] = com.pdfservice.corba.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/InvalidParameterException:1.0"))
                    throw com.pdfservice.corba.InvalidParameterExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/PDFPasswordException:1.0"))
                    throw com.pdfservice.corba.PDFPasswordExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extractPages (pdfFile, pages        );
            } finally {
                _releaseReply ($in);
            }
  } // extractPages


  /**
           * Supprime des pages spécifiques d'un PDF.
           * @param pdfFile   PDF source en bytes
           * @param pages     liste de numéros de pages à supprimer (base 1)
           * @return          PDF sans les pages supprimées
           */
  public byte[] deletePages (byte[] pdfFile, int[] pages) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deletePages", true);
                com.pdfservice.corba.ByteArrayHelper.write ($out, pdfFile);
                com.pdfservice.corba.LongListHelper.write ($out, pages);
                $in = _invoke ($out);
                byte $result[] = com.pdfservice.corba.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/InvalidParameterException:1.0"))
                    throw com.pdfservice.corba.InvalidParameterExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/PDFPasswordException:1.0"))
                    throw com.pdfservice.corba.PDFPasswordExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return deletePages (pdfFile, pages        );
            } finally {
                _releaseReply ($in);
            }
  } // deletePages


  /**
           * Protège un PDF avec un mot de passe (chiffrement AES-256).
           * @param pdfFile       PDF source en bytes
           * @param userPassword  mot de passe utilisateur
           * @param ownerPassword mot de passe propriétaire
           * @return              PDF chiffré en bytes
           */
  public byte[] encrypt (byte[] pdfFile, String userPassword, String ownerPassword) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFEncryptionException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("encrypt", true);
                com.pdfservice.corba.ByteArrayHelper.write ($out, pdfFile);
                $out.write_string (userPassword);
                $out.write_string (ownerPassword);
                $in = _invoke ($out);
                byte $result[] = com.pdfservice.corba.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/InvalidParameterException:1.0"))
                    throw com.pdfservice.corba.InvalidParameterExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/PDFEncryptionException:1.0"))
                    throw com.pdfservice.corba.PDFEncryptionExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return encrypt (pdfFile, userPassword, ownerPassword        );
            } finally {
                _releaseReply ($in);
            }
  } // encrypt


  /**
           * Convertit chaque page d'un PDF en image PNG.
           * @param pdfFile   PDF source en bytes
           * @param dpi       résolution de sortie (ex: 150, 300)
           * @param password  mot de passe si PDF chiffré (vide si aucun)
           * @return          ImageConversionResult
           */
  public com.pdfservice.corba.ImageConversionResult toImages (byte[] pdfFile, int dpi, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("toImages", true);
                com.pdfservice.corba.ByteArrayHelper.write ($out, pdfFile);
                $out.write_long (dpi);
                $out.write_string (password);
                $in = _invoke ($out);
                com.pdfservice.corba.ImageConversionResult $result = com.pdfservice.corba.ImageConversionResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/InvalidParameterException:1.0"))
                    throw com.pdfservice.corba.InvalidParameterExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/PDFPasswordException:1.0"))
                    throw com.pdfservice.corba.PDFPasswordExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return toImages (pdfFile, dpi, password        );
            } finally {
                _releaseReply ($in);
            }
  } // toImages


  /**
           * Extrait tout le texte d'un PDF.
           * @param pdfFile   PDF source en bytes
           * @param password  mot de passe si PDF chiffré (vide si aucun)
           * @return          TextExtractionResult
           */
  public com.pdfservice.corba.TextExtractionResult extractText (byte[] pdfFile, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.PDFPasswordException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extractText", true);
                com.pdfservice.corba.ByteArrayHelper.write ($out, pdfFile);
                $out.write_string (password);
                $in = _invoke ($out);
                com.pdfservice.corba.TextExtractionResult $result = com.pdfservice.corba.TextExtractionResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/PDFPasswordException:1.0"))
                    throw com.pdfservice.corba.PDFPasswordExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extractText (pdfFile, password        );
            } finally {
                _releaseReply ($in);
            }
  } // extractText


  /**
           * Crée un nouveau PDF à partir d'un contenu texte.
           * @param title    titre du document
           * @param content  contenu texte (supporte \n pour sauts de ligne)
           * @param author   auteur du document
           * @return         PDF créé en bytes
           */
  public byte[] createPDF (String title, String content, String author) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createPDF", true);
                $out.write_string (title);
                $out.write_string (content);
                $out.write_string (author);
                $in = _invoke ($out);
                byte $result[] = com.pdfservice.corba.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/InvalidParameterException:1.0"))
                    throw com.pdfservice.corba.InvalidParameterExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createPDF (title, content, author        );
            } finally {
                _releaseReply ($in);
            }
  } // createPDF


  /**
           * Compresse un PDF en réduisant la qualité des images embarquées.
           * @param pdfFile  PDF source en bytes
           * @param params   paramètres de compression
           * @return         PDF compressé en bytes
           */
  public byte[] compress (byte[] pdfFile, com.pdfservice.corba.CompressionParams params) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("compress", true);
                com.pdfservice.corba.ByteArrayHelper.write ($out, pdfFile);
                com.pdfservice.corba.CompressionParamsHelper.write ($out, params);
                $in = _invoke ($out);
                byte $result[] = com.pdfservice.corba.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/InvalidParameterException:1.0"))
                    throw com.pdfservice.corba.InvalidParameterExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return compress (pdfFile, params        );
            } finally {
                _releaseReply ($in);
            }
  } // compress


  /**
           * Applique un filigrane textuel sur les pages d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param params   paramètres du filigrane
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         PDF avec filigrane en bytes
           */
  public byte[] addWatermark (byte[] pdfFile, com.pdfservice.corba.WatermarkParams params, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addWatermark", true);
                com.pdfservice.corba.ByteArrayHelper.write ($out, pdfFile);
                com.pdfservice.corba.WatermarkParamsHelper.write ($out, params);
                $out.write_string (password);
                $in = _invoke ($out);
                byte $result[] = com.pdfservice.corba.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/InvalidParameterException:1.0"))
                    throw com.pdfservice.corba.InvalidParameterExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/PDFPasswordException:1.0"))
                    throw com.pdfservice.corba.PDFPasswordExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addWatermark (pdfFile, params, password        );
            } finally {
                _releaseReply ($in);
            }
  } // addWatermark


  /**
           * Fait pivoter des pages d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param params   paramètres de rotation
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         PDF avec pages pivotées
           */
  public byte[] rotatePages (byte[] pdfFile, com.pdfservice.corba.RotationParams params, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("rotatePages", true);
                com.pdfservice.corba.ByteArrayHelper.write ($out, pdfFile);
                com.pdfservice.corba.RotationParamsHelper.write ($out, params);
                $out.write_string (password);
                $in = _invoke ($out);
                byte $result[] = com.pdfservice.corba.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/InvalidParameterException:1.0"))
                    throw com.pdfservice.corba.InvalidParameterExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/PDFPasswordException:1.0"))
                    throw com.pdfservice.corba.PDFPasswordExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return rotatePages (pdfFile, params, password        );
            } finally {
                _releaseReply ($in);
            }
  } // rotatePages


  /**
           * Extrait toutes les images embarquées d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         EmbeddedImageResult
           */
  public com.pdfservice.corba.EmbeddedImageResult extractImages (byte[] pdfFile, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.PDFPasswordException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extractImages", true);
                com.pdfservice.corba.ByteArrayHelper.write ($out, pdfFile);
                $out.write_string (password);
                $in = _invoke ($out);
                com.pdfservice.corba.EmbeddedImageResult $result = com.pdfservice.corba.EmbeddedImageResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/PDFPasswordException:1.0"))
                    throw com.pdfservice.corba.PDFPasswordExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extractImages (pdfFile, password        );
            } finally {
                _releaseReply ($in);
            }
  } // extractImages


  /**
           * Retourne les métadonnées d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         PDFMetadata
           */
  public com.pdfservice.corba.PDFMetadata getMetadata (byte[] pdfFile, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.PDFPasswordException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMetadata", true);
                com.pdfservice.corba.ByteArrayHelper.write ($out, pdfFile);
                $out.write_string (password);
                $in = _invoke ($out);
                com.pdfservice.corba.PDFMetadata $result = com.pdfservice.corba.PDFMetadataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:com/pdfservice/corba/PDFProcessingException:1.0"))
                    throw com.pdfservice.corba.PDFProcessingExceptionHelper.read ($in);
                else if (_id.equals ("IDL:com/pdfservice/corba/PDFPasswordException:1.0"))
                    throw com.pdfservice.corba.PDFPasswordExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMetadata (pdfFile, password        );
            } finally {
                _releaseReply ($in);
            }
  } // getMetadata


  /**
           * Vérifie que le service est opérationnel (health check).
           * @return "OK" si le service répond
           */
  public String ping ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ping", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ping (        );
            } finally {
                _releaseReply ($in);
            }
  } // ping

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/pdfservice/corba/IPDFService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IPDFServiceStub
