package com.pdfservice.corba;


/**
* com/pdfservice/corba/ByteArrayListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

public final class ByteArrayListHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[][] = null;

  public ByteArrayListHolder ()
  {
  }

  public ByteArrayListHolder (byte[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.pdfservice.corba.ByteArrayListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.pdfservice.corba.ByteArrayListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.pdfservice.corba.ByteArrayListHelper.type ();
  }

}
