package com.pdfservice.corba;


/**
* com/pdfservice/corba/CompressionParamsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

abstract public class CompressionParamsHelper
{
  private static String  _id = "IDL:com/pdfservice/corba/CompressionParams:1.0";

  public static void insert (org.omg.CORBA.Any a, com.pdfservice.corba.CompressionParams that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.pdfservice.corba.CompressionParams extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "dpi",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[1] = new org.omg.CORBA.StructMember (
            "compressImages",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[2] = new org.omg.CORBA.StructMember (
            "removeMetadata",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.pdfservice.corba.CompressionParamsHelper.id (), "CompressionParams", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.pdfservice.corba.CompressionParams read (org.omg.CORBA.portable.InputStream istream)
  {
    com.pdfservice.corba.CompressionParams value = new com.pdfservice.corba.CompressionParams ();
    value.dpi = istream.read_long ();
    value.compressImages = istream.read_boolean ();
    value.removeMetadata = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.pdfservice.corba.CompressionParams value)
  {
    ostream.write_long (value.dpi);
    ostream.write_boolean (value.compressImages);
    ostream.write_boolean (value.removeMetadata);
  }

}
