package com.pdfservice.corba;

/**
* com/pdfservice/corba/EmbeddedImageResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:48 AM GMT
*/

public final class EmbeddedImageResultHolder implements org.omg.CORBA.portable.Streamable
{
  public com.pdfservice.corba.EmbeddedImageResult value = null;

  public EmbeddedImageResultHolder ()
  {
  }

  public EmbeddedImageResultHolder (com.pdfservice.corba.EmbeddedImageResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.pdfservice.corba.EmbeddedImageResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.pdfservice.corba.EmbeddedImageResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.pdfservice.corba.EmbeddedImageResultHelper.type ();
  }

}
