package com.pdfservice.corba;


/**
* com/pdfservice/corba/EmbeddedImageResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:48 AM GMT
*/

public final class EmbeddedImageResult implements org.omg.CORBA.portable.IDLEntity
{
  public byte images[][] = null;
  public String mimeTypes[] = null;
  public int imageCount = (int)0;

  public EmbeddedImageResult ()
  {
  } // ctor

  public EmbeddedImageResult (byte[][] _images, String[] _mimeTypes, int _imageCount)
  {
    images = _images;
    mimeTypes = _mimeTypes;
    imageCount = _imageCount;
  } // ctor

} // class EmbeddedImageResult
