package com.pdfservice.corba;

/**
* com/pdfservice/corba/ImageConversionResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

public final class ImageConversionResultHolder implements org.omg.CORBA.portable.Streamable
{
  public com.pdfservice.corba.ImageConversionResult value = null;

  public ImageConversionResultHolder ()
  {
  }

  public ImageConversionResultHolder (com.pdfservice.corba.ImageConversionResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.pdfservice.corba.ImageConversionResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.pdfservice.corba.ImageConversionResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.pdfservice.corba.ImageConversionResultHelper.type ();
  }

}
