package com.pdfservice.corba;


/**
* com/pdfservice/corba/IPDFServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:48 AM GMT
*/


// ----------------------------------------------------------
public abstract class IPDFServicePOA extends org.omg.PortableServer.Servant
 implements com.pdfservice.corba.IPDFServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("merge", new java.lang.Integer (0));
    _methods.put ("split", new java.lang.Integer (1));
    _methods.put ("extractPages", new java.lang.Integer (2));
    _methods.put ("deletePages", new java.lang.Integer (3));
    _methods.put ("encrypt", new java.lang.Integer (4));
    _methods.put ("toImages", new java.lang.Integer (5));
    _methods.put ("extractText", new java.lang.Integer (6));
    _methods.put ("createPDF", new java.lang.Integer (7));
    _methods.put ("compress", new java.lang.Integer (8));
    _methods.put ("addWatermark", new java.lang.Integer (9));
    _methods.put ("rotatePages", new java.lang.Integer (10));
    _methods.put ("extractImages", new java.lang.Integer (11));
    _methods.put ("getMetadata", new java.lang.Integer (12));
    _methods.put ("ping", new java.lang.Integer (13));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /**
           * Fusionne plusieurs PDFs en un seul.
           * @param pdfFiles  liste de PDF en bytes
           * @return          PDF fusionné en bytes
           */
       case 0:  // com/pdfservice/corba/IPDFService/merge
       {
         try {
           byte pdfFiles[][] = com.pdfservice.corba.ByteArrayListHelper.read (in);
           byte $result[] = null;
           $result = this.merge (pdfFiles);
           out = $rh.createReply();
           com.pdfservice.corba.ByteArrayHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.InvalidParameterException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.InvalidParameterExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Découpe un PDF en plusieurs fichiers selon un intervalle.
           * @param pdfFile       PDF source en bytes
           * @param pagesPerPart  nombre de pages par partie
           * @return              SplitResult avec liste de PDFs
           */
       case 1:  // com/pdfservice/corba/IPDFService/split
       {
         try {
           byte pdfFile[] = com.pdfservice.corba.ByteArrayHelper.read (in);
           int pagesPerPart = in.read_long ();
           com.pdfservice.corba.SplitResult $result = null;
           $result = this.split (pdfFile, pagesPerPart);
           out = $rh.createReply();
           com.pdfservice.corba.SplitResultHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.InvalidParameterException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.InvalidParameterExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.PDFPasswordException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFPasswordExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Extrait des pages spécifiques dans un nouveau PDF.
           * @param pdfFile   PDF source en bytes
           * @param pages     liste de numéros de pages (base 1)
           * @return          PDF avec les pages extraites
           */
       case 2:  // com/pdfservice/corba/IPDFService/extractPages
       {
         try {
           byte pdfFile[] = com.pdfservice.corba.ByteArrayHelper.read (in);
           int pages[] = com.pdfservice.corba.LongListHelper.read (in);
           byte $result[] = null;
           $result = this.extractPages (pdfFile, pages);
           out = $rh.createReply();
           com.pdfservice.corba.ByteArrayHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.InvalidParameterException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.InvalidParameterExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.PDFPasswordException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFPasswordExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Supprime des pages spécifiques d'un PDF.
           * @param pdfFile   PDF source en bytes
           * @param pages     liste de numéros de pages à supprimer (base 1)
           * @return          PDF sans les pages supprimées
           */
       case 3:  // com/pdfservice/corba/IPDFService/deletePages
       {
         try {
           byte pdfFile[] = com.pdfservice.corba.ByteArrayHelper.read (in);
           int pages[] = com.pdfservice.corba.LongListHelper.read (in);
           byte $result[] = null;
           $result = this.deletePages (pdfFile, pages);
           out = $rh.createReply();
           com.pdfservice.corba.ByteArrayHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.InvalidParameterException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.InvalidParameterExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.PDFPasswordException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFPasswordExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Protège un PDF avec un mot de passe (chiffrement AES-256).
           * @param pdfFile       PDF source en bytes
           * @param userPassword  mot de passe utilisateur
           * @param ownerPassword mot de passe propriétaire
           * @return              PDF chiffré en bytes
           */
       case 4:  // com/pdfservice/corba/IPDFService/encrypt
       {
         try {
           byte pdfFile[] = com.pdfservice.corba.ByteArrayHelper.read (in);
           String userPassword = in.read_string ();
           String ownerPassword = in.read_string ();
           byte $result[] = null;
           $result = this.encrypt (pdfFile, userPassword, ownerPassword);
           out = $rh.createReply();
           com.pdfservice.corba.ByteArrayHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.InvalidParameterException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.InvalidParameterExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.PDFEncryptionException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFEncryptionExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Convertit chaque page d'un PDF en image PNG.
           * @param pdfFile   PDF source en bytes
           * @param dpi       résolution de sortie (ex: 150, 300)
           * @param password  mot de passe si PDF chiffré (vide si aucun)
           * @return          ImageConversionResult
           */
       case 5:  // com/pdfservice/corba/IPDFService/toImages
       {
         try {
           byte pdfFile[] = com.pdfservice.corba.ByteArrayHelper.read (in);
           int dpi = in.read_long ();
           String password = in.read_string ();
           com.pdfservice.corba.ImageConversionResult $result = null;
           $result = this.toImages (pdfFile, dpi, password);
           out = $rh.createReply();
           com.pdfservice.corba.ImageConversionResultHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.InvalidParameterException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.InvalidParameterExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.PDFPasswordException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFPasswordExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Extrait tout le texte d'un PDF.
           * @param pdfFile   PDF source en bytes
           * @param password  mot de passe si PDF chiffré (vide si aucun)
           * @return          TextExtractionResult
           */
       case 6:  // com/pdfservice/corba/IPDFService/extractText
       {
         try {
           byte pdfFile[] = com.pdfservice.corba.ByteArrayHelper.read (in);
           String password = in.read_string ();
           com.pdfservice.corba.TextExtractionResult $result = null;
           $result = this.extractText (pdfFile, password);
           out = $rh.createReply();
           com.pdfservice.corba.TextExtractionResultHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.PDFPasswordException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFPasswordExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Crée un nouveau PDF à partir d'un contenu texte.
           * @param title    titre du document
           * @param content  contenu texte (supporte \n pour sauts de ligne)
           * @param author   auteur du document
           * @return         PDF créé en bytes
           */
       case 7:  // com/pdfservice/corba/IPDFService/createPDF
       {
         try {
           String title = in.read_string ();
           String content = in.read_string ();
           String author = in.read_string ();
           byte $result[] = null;
           $result = this.createPDF (title, content, author);
           out = $rh.createReply();
           com.pdfservice.corba.ByteArrayHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.InvalidParameterException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.InvalidParameterExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Compresse un PDF en réduisant la qualité des images embarquées.
           * @param pdfFile  PDF source en bytes
           * @param params   paramètres de compression
           * @return         PDF compressé en bytes
           */
       case 8:  // com/pdfservice/corba/IPDFService/compress
       {
         try {
           byte pdfFile[] = com.pdfservice.corba.ByteArrayHelper.read (in);
           com.pdfservice.corba.CompressionParams params = com.pdfservice.corba.CompressionParamsHelper.read (in);
           byte $result[] = null;
           $result = this.compress (pdfFile, params);
           out = $rh.createReply();
           com.pdfservice.corba.ByteArrayHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.InvalidParameterException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.InvalidParameterExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Applique un filigrane textuel sur les pages d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param params   paramètres du filigrane
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         PDF avec filigrane en bytes
           */
       case 9:  // com/pdfservice/corba/IPDFService/addWatermark
       {
         try {
           byte pdfFile[] = com.pdfservice.corba.ByteArrayHelper.read (in);
           com.pdfservice.corba.WatermarkParams params = com.pdfservice.corba.WatermarkParamsHelper.read (in);
           String password = in.read_string ();
           byte $result[] = null;
           $result = this.addWatermark (pdfFile, params, password);
           out = $rh.createReply();
           com.pdfservice.corba.ByteArrayHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.InvalidParameterException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.InvalidParameterExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.PDFPasswordException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFPasswordExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Fait pivoter des pages d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param params   paramètres de rotation
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         PDF avec pages pivotées
           */
       case 10:  // com/pdfservice/corba/IPDFService/rotatePages
       {
         try {
           byte pdfFile[] = com.pdfservice.corba.ByteArrayHelper.read (in);
           com.pdfservice.corba.RotationParams params = com.pdfservice.corba.RotationParamsHelper.read (in);
           String password = in.read_string ();
           byte $result[] = null;
           $result = this.rotatePages (pdfFile, params, password);
           out = $rh.createReply();
           com.pdfservice.corba.ByteArrayHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.InvalidParameterException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.InvalidParameterExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.PDFPasswordException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFPasswordExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Extrait toutes les images embarquées d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         EmbeddedImageResult
           */
       case 11:  // com/pdfservice/corba/IPDFService/extractImages
       {
         try {
           byte pdfFile[] = com.pdfservice.corba.ByteArrayHelper.read (in);
           String password = in.read_string ();
           com.pdfservice.corba.EmbeddedImageResult $result = null;
           $result = this.extractImages (pdfFile, password);
           out = $rh.createReply();
           com.pdfservice.corba.EmbeddedImageResultHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.PDFPasswordException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFPasswordExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Retourne les métadonnées d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         PDFMetadata
           */
       case 12:  // com/pdfservice/corba/IPDFService/getMetadata
       {
         try {
           byte pdfFile[] = com.pdfservice.corba.ByteArrayHelper.read (in);
           String password = in.read_string ();
           com.pdfservice.corba.PDFMetadata $result = null;
           $result = this.getMetadata (pdfFile, password);
           out = $rh.createReply();
           com.pdfservice.corba.PDFMetadataHelper.write (out, $result);
         } catch (com.pdfservice.corba.PDFProcessingException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFProcessingExceptionHelper.write (out, $ex);
         } catch (com.pdfservice.corba.PDFPasswordException $ex) {
           out = $rh.createExceptionReply ();
           com.pdfservice.corba.PDFPasswordExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
           * Vérifie que le service est opérationnel (health check).
           * @return "OK" si le service répond
           */
       case 13:  // com/pdfservice/corba/IPDFService/ping
       {
         String $result = null;
         $result = this.ping ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/pdfservice/corba/IPDFService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IPDFService _this() 
  {
    return IPDFServiceHelper.narrow(
    super._this_object());
  }

  public IPDFService _this(org.omg.CORBA.ORB orb) 
  {
    return IPDFServiceHelper.narrow(
    super._this_object(orb));
  }


} // class IPDFServicePOA
