package com.pdfservice.corba;


/**
* com/pdfservice/corba/IPDFServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:48 AM GMT
*/


// ----------------------------------------------------------
abstract public class IPDFServiceHelper
{
  private static String  _id = "IDL:com/pdfservice/corba/IPDFService:1.0";

  public static void insert (org.omg.CORBA.Any a, com.pdfservice.corba.IPDFService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.pdfservice.corba.IPDFService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.pdfservice.corba.IPDFServiceHelper.id (), "IPDFService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.pdfservice.corba.IPDFService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IPDFServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.pdfservice.corba.IPDFService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.pdfservice.corba.IPDFService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.pdfservice.corba.IPDFService)
      return (com.pdfservice.corba.IPDFService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.pdfservice.corba._IPDFServiceStub stub = new com.pdfservice.corba._IPDFServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.pdfservice.corba.IPDFService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.pdfservice.corba.IPDFService)
      return (com.pdfservice.corba.IPDFService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.pdfservice.corba._IPDFServiceStub stub = new com.pdfservice.corba._IPDFServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
