package com.pdfservice.corba;


/**
* com/pdfservice/corba/IPDFService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:48 AM GMT
*/


// ----------------------------------------------------------
public interface IPDFService extends IPDFServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPDFService
