package com.pdfservice.corba;


/**
* com/pdfservice/corba/IPDFServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:48 AM GMT
*/


// ----------------------------------------------------------
public interface IPDFServiceOperations 
{

  /**
           * Fusionne plusieurs PDFs en un seul.
           * @param pdfFiles  liste de PDF en bytes
           * @return          PDF fusionné en bytes
           */
  byte[] merge (byte[][] pdfFiles) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException;

  /**
           * Découpe un PDF en plusieurs fichiers selon un intervalle.
           * @param pdfFile       PDF source en bytes
           * @param pagesPerPart  nombre de pages par partie
           * @return              SplitResult avec liste de PDFs
           */
  com.pdfservice.corba.SplitResult split (byte[] pdfFile, int pagesPerPart) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException;

  /**
           * Extrait des pages spécifiques dans un nouveau PDF.
           * @param pdfFile   PDF source en bytes
           * @param pages     liste de numéros de pages (base 1)
           * @return          PDF avec les pages extraites
           */
  byte[] extractPages (byte[] pdfFile, int[] pages) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException;

  /**
           * Supprime des pages spécifiques d'un PDF.
           * @param pdfFile   PDF source en bytes
           * @param pages     liste de numéros de pages à supprimer (base 1)
           * @return          PDF sans les pages supprimées
           */
  byte[] deletePages (byte[] pdfFile, int[] pages) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException;

  /**
           * Protège un PDF avec un mot de passe (chiffrement AES-256).
           * @param pdfFile       PDF source en bytes
           * @param userPassword  mot de passe utilisateur
           * @param ownerPassword mot de passe propriétaire
           * @return              PDF chiffré en bytes
           */
  byte[] encrypt (byte[] pdfFile, String userPassword, String ownerPassword) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFEncryptionException;

  /**
           * Convertit chaque page d'un PDF en image PNG.
           * @param pdfFile   PDF source en bytes
           * @param dpi       résolution de sortie (ex: 150, 300)
           * @param password  mot de passe si PDF chiffré (vide si aucun)
           * @return          ImageConversionResult
           */
  com.pdfservice.corba.ImageConversionResult toImages (byte[] pdfFile, int dpi, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException;

  /**
           * Extrait tout le texte d'un PDF.
           * @param pdfFile   PDF source en bytes
           * @param password  mot de passe si PDF chiffré (vide si aucun)
           * @return          TextExtractionResult
           */
  com.pdfservice.corba.TextExtractionResult extractText (byte[] pdfFile, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.PDFPasswordException;

  /**
           * Crée un nouveau PDF à partir d'un contenu texte.
           * @param title    titre du document
           * @param content  contenu texte (supporte \n pour sauts de ligne)
           * @param author   auteur du document
           * @return         PDF créé en bytes
           */
  byte[] createPDF (String title, String content, String author) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException;

  /**
           * Compresse un PDF en réduisant la qualité des images embarquées.
           * @param pdfFile  PDF source en bytes
           * @param params   paramètres de compression
           * @return         PDF compressé en bytes
           */
  byte[] compress (byte[] pdfFile, com.pdfservice.corba.CompressionParams params) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException;

  /**
           * Applique un filigrane textuel sur les pages d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param params   paramètres du filigrane
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         PDF avec filigrane en bytes
           */
  byte[] addWatermark (byte[] pdfFile, com.pdfservice.corba.WatermarkParams params, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException;

  /**
           * Fait pivoter des pages d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param params   paramètres de rotation
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         PDF avec pages pivotées
           */
  byte[] rotatePages (byte[] pdfFile, com.pdfservice.corba.RotationParams params, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.InvalidParameterException, com.pdfservice.corba.PDFPasswordException;

  /**
           * Extrait toutes les images embarquées d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         EmbeddedImageResult
           */
  com.pdfservice.corba.EmbeddedImageResult extractImages (byte[] pdfFile, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.PDFPasswordException;

  /**
           * Retourne les métadonnées d'un PDF.
           * @param pdfFile  PDF source en bytes
           * @param password mot de passe si PDF chiffré (vide si aucun)
           * @return         PDFMetadata
           */
  com.pdfservice.corba.PDFMetadata getMetadata (byte[] pdfFile, String password) throws com.pdfservice.corba.PDFProcessingException, com.pdfservice.corba.PDFPasswordException;

  /**
           * Vérifie que le service est opérationnel (health check).
           * @return "OK" si le service répond
           */
  String ping ();
} // interface IPDFServiceOperations
