package com.pdfservice.corba;


/**
* com/pdfservice/corba/PDFEncryptionException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

public final class PDFEncryptionException extends org.omg.CORBA.UserException
{
  public String message = null;

  public PDFEncryptionException ()
  {
    super(PDFEncryptionExceptionHelper.id());
  } // ctor

  public PDFEncryptionException (String _message)
  {
    super(PDFEncryptionExceptionHelper.id());
    message = _message;
  } // ctor


  public PDFEncryptionException (String $reason, String _message)
  {
    super(PDFEncryptionExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class PDFEncryptionException
