package com.pdfservice.corba;

/**
* com/pdfservice/corba/PDFEncryptionExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

public final class PDFEncryptionExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.pdfservice.corba.PDFEncryptionException value = null;

  public PDFEncryptionExceptionHolder ()
  {
  }

  public PDFEncryptionExceptionHolder (com.pdfservice.corba.PDFEncryptionException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.pdfservice.corba.PDFEncryptionExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.pdfservice.corba.PDFEncryptionExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.pdfservice.corba.PDFEncryptionExceptionHelper.type ();
  }

}
