package com.pdfservice.corba;


/**
* com/pdfservice/corba/PDFMetadataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

abstract public class PDFMetadataHelper
{
  private static String  _id = "IDL:com/pdfservice/corba/PDFMetadata:1.0";

  public static void insert (org.omg.CORBA.Any a, com.pdfservice.corba.PDFMetadata that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.pdfservice.corba.PDFMetadata extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [8];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "title",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "author",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "subject",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "creator",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "pageCount",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "fileSizeBytes",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[6] = new org.omg.CORBA.StructMember (
            "isEncrypted",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "pdfVersion",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.pdfservice.corba.PDFMetadataHelper.id (), "PDFMetadata", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.pdfservice.corba.PDFMetadata read (org.omg.CORBA.portable.InputStream istream)
  {
    com.pdfservice.corba.PDFMetadata value = new com.pdfservice.corba.PDFMetadata ();
    value.title = istream.read_string ();
    value.author = istream.read_string ();
    value.subject = istream.read_string ();
    value.creator = istream.read_string ();
    value.pageCount = istream.read_long ();
    value.fileSizeBytes = istream.read_long ();
    value.isEncrypted = istream.read_boolean ();
    value.pdfVersion = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.pdfservice.corba.PDFMetadata value)
  {
    ostream.write_string (value.title);
    ostream.write_string (value.author);
    ostream.write_string (value.subject);
    ostream.write_string (value.creator);
    ostream.write_long (value.pageCount);
    ostream.write_long (value.fileSizeBytes);
    ostream.write_boolean (value.isEncrypted);
    ostream.write_string (value.pdfVersion);
  }

}
