package com.pdfservice.corba;


/**
* com/pdfservice/corba/PDFProcessingException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

public final class PDFProcessingException extends org.omg.CORBA.UserException
{
  public String message = null;
  public String errorCode = null;

  public PDFProcessingException ()
  {
    super(PDFProcessingExceptionHelper.id());
  } // ctor

  public PDFProcessingException (String _message, String _errorCode)
  {
    super(PDFProcessingExceptionHelper.id());
    message = _message;
    errorCode = _errorCode;
  } // ctor


  public PDFProcessingException (String $reason, String _message, String _errorCode)
  {
    super(PDFProcessingExceptionHelper.id() + "  " + $reason);
    message = _message;
    errorCode = _errorCode;
  } // ctor

} // class PDFProcessingException
