package com.pdfservice.corba;

/**
* com/pdfservice/corba/PDFProcessingExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

public final class PDFProcessingExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.pdfservice.corba.PDFProcessingException value = null;

  public PDFProcessingExceptionHolder ()
  {
  }

  public PDFProcessingExceptionHolder (com.pdfservice.corba.PDFProcessingException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.pdfservice.corba.PDFProcessingExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.pdfservice.corba.PDFProcessingExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.pdfservice.corba.PDFProcessingExceptionHelper.type ();
  }

}
