package com.pdfservice.corba;


/**
* com/pdfservice/corba/RotationParamsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

abstract public class RotationParamsHelper
{
  private static String  _id = "IDL:com/pdfservice/corba/RotationParams:1.0";

  public static void insert (org.omg.CORBA.Any a, com.pdfservice.corba.RotationParams that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.pdfservice.corba.RotationParams extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (com.pdfservice.corba.LongListHelper.id (), "LongList", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "pages",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "degrees",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.pdfservice.corba.RotationParamsHelper.id (), "RotationParams", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.pdfservice.corba.RotationParams read (org.omg.CORBA.portable.InputStream istream)
  {
    com.pdfservice.corba.RotationParams value = new com.pdfservice.corba.RotationParams ();
    value.pages = com.pdfservice.corba.LongListHelper.read (istream);
    value.degrees = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.pdfservice.corba.RotationParams value)
  {
    com.pdfservice.corba.LongListHelper.write (ostream, value.pages);
    ostream.write_long (value.degrees);
  }

}
