package com.pdfservice.corba;


/**
* com/pdfservice/corba/RotationParams.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

public final class RotationParams implements org.omg.CORBA.portable.IDLEntity
{
  public int pages[] = null;

  // numéros de pages (base 1), vide = toutes
  public int degrees = (int)0;

  public RotationParams ()
  {
  } // ctor

  public RotationParams (int[] _pages, int _degrees)
  {
    pages = _pages;
    degrees = _degrees;
  } // ctor

} // class RotationParams
