package com.pdfservice.corba;


/**
* com/pdfservice/corba/SplitResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:48 AM GMT
*/

public final class SplitResult implements org.omg.CORBA.portable.IDLEntity
{
  public byte parts[][] = null;
  public int partCount = (int)0;

  public SplitResult ()
  {
  } // ctor

  public SplitResult (byte[][] _parts, int _partCount)
  {
    parts = _parts;
    partCount = _partCount;
  } // ctor

} // class SplitResult
