package com.pdfservice.corba;

/**
* com/pdfservice/corba/SplitResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:48 AM GMT
*/

public final class SplitResultHolder implements org.omg.CORBA.portable.Streamable
{
  public com.pdfservice.corba.SplitResult value = null;

  public SplitResultHolder ()
  {
  }

  public SplitResultHolder (com.pdfservice.corba.SplitResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.pdfservice.corba.SplitResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.pdfservice.corba.SplitResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.pdfservice.corba.SplitResultHelper.type ();
  }

}
