package com.pdfservice.corba;


/**
* com/pdfservice/corba/TextExtractionResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

public final class TextExtractionResult implements org.omg.CORBA.portable.IDLEntity
{
  public String fullText = null;
  public String pageTexts[] = null;

  // texte par page
  public int pageCount = (int)0;

  public TextExtractionResult ()
  {
  } // ctor

  public TextExtractionResult (String _fullText, String[] _pageTexts, int _pageCount)
  {
    fullText = _fullText;
    pageTexts = _pageTexts;
    pageCount = _pageCount;
  } // ctor

} // class TextExtractionResult
