package com.pdfservice.corba;


/**
* com/pdfservice/corba/WatermarkParamsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/service.idl
* Sunday, May 10, 2026 8:55:47 AM GMT
*/

abstract public class WatermarkParamsHelper
{
  private static String  _id = "IDL:com/pdfservice/corba/WatermarkParams:1.0";

  public static void insert (org.omg.CORBA.Any a, com.pdfservice.corba.WatermarkParams that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.pdfservice.corba.WatermarkParams extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [9];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "text",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[1] = new org.omg.CORBA.StructMember (
            "fontSize",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[2] = new org.omg.CORBA.StructMember (
            "opacity",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[3] = new org.omg.CORBA.StructMember (
            "rotationDegrees",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "colorR",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "colorG",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[6] = new org.omg.CORBA.StructMember (
            "colorB",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[7] = new org.omg.CORBA.StructMember (
            "applyToAllPages",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (com.pdfservice.corba.LongListHelper.id (), "LongList", _tcOf_members0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "targetPages",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.pdfservice.corba.WatermarkParamsHelper.id (), "WatermarkParams", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.pdfservice.corba.WatermarkParams read (org.omg.CORBA.portable.InputStream istream)
  {
    com.pdfservice.corba.WatermarkParams value = new com.pdfservice.corba.WatermarkParams ();
    value.text = istream.read_string ();
    value.fontSize = istream.read_float ();
    value.opacity = istream.read_float ();
    value.rotationDegrees = istream.read_float ();
    value.colorR = istream.read_long ();
    value.colorG = istream.read_long ();
    value.colorB = istream.read_long ();
    value.applyToAllPages = istream.read_boolean ();
    value.targetPages = com.pdfservice.corba.LongListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.pdfservice.corba.WatermarkParams value)
  {
    ostream.write_string (value.text);
    ostream.write_float (value.fontSize);
    ostream.write_float (value.opacity);
    ostream.write_float (value.rotationDegrees);
    ostream.write_long (value.colorR);
    ostream.write_long (value.colorG);
    ostream.write_long (value.colorB);
    ostream.write_boolean (value.applyToAllPages);
    com.pdfservice.corba.LongListHelper.write (ostream, value.targetPages);
  }

}
